### PR TITLE
 fix: Switch to JingMatrix/LSPatch to resolve patching on Android 15

### PR DESCRIPTION
**Pull request by Ushie**

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please mention the source of these binary blobs.

**Comment by Ushie** [comment]
All the files originate from this action build: https://github.com/JingMatrix/LSPatch/actions/runs/11613450774/artifacts/2128595422

The .jar was converted to .aar with the convert-lspatch.sh script in this repository, and the liblspatch.so binaries were extracted from the manager.apk in that artifact

**Comment by oSumAtrIX** [comment]
I don't like the lack of audibility since we are committing binary blobs with no public workflow that generated them, essentially trusting you. Is it possible, to publicly generate the files you're committing?

**Comment by Ushie** [comment]
You might've missed my previous comment, the binary blobs checked into this PR are verifiable against the hashes of the workflow I linked

**Pull request merged**
